config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  devise_for :users
  root 'static_pages#home'
  get 'help', to: 'static_pages#help'
  get 'about', to: 'static_pages#about'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :roster
end

app/models/roster.rb
class Roster < ApplicationRecord
  has_many :participants
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_world_controller.rb
# frozen_string_literal: true

class HelloWorldController < ApplicationController
  layout "hello_world"

  def index
    @hello_world_props = { name: "Stranger" }
  end
end

app/controllers/rosters_controller.rb
# frozen_string_literal: true

class RostersController < ApplicationController
  before_action :set_roster, only: %i[show edit update destroy]

  # GET /rosters
  # GET /rosters.json
  def index
    @rosters = Roster.all
  end

  # GET /rosters/1
  # GET /rosters/1.json
  def show; end

  # GET /rosters/new
  def new
    @roster = Roster.new
  end

  # GET /rosters/1/edit
  def edit; end

  # POST /rosters
  # POST /rosters.json
  def create
    @roster = Roster.new(roster_params)

    respond_to do |format|
      if @roster.save
        format.html { redirect_to @roster, notice: 'Roster was successfully created.' }
        format.json { render :show, status: :created, location: @roster }
      else
        format.html { render :new }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rosters/1
  # PATCH/PUT /rosters/1.json
  def update
    respond_to do |format|
      if @roster.update(roster_params)
        format.html { redirect_to @roster, notice: 'Roster was successfully updated.' }
        format.json { render :show, status: :ok, location: @roster }
      else
        format.html { render :edit }
        format.json { render json: @roster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rosters/1
  # DELETE /rosters/1.json
  def destroy
    @roster.destroy
    respond_to do |format|
      format.html { redirect_to rosters_url, notice: 'Roster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_roster
    @roster = Roster.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def roster_params
    params.require(:roster).permit(:name, :extra_attributes)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # Returns the full title on a per-page basis.
    def full_title(page_title = '')
        base_title = "RHM"
        if page_title.empty?
            base_title
        else 
            page_title + " | " + base_title
        end
    end
end

app/helpers/rosters_helper.rb
module RostersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Reindeer Hunt Manager &copy; 2019 Kyle Anderson.
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
    </ul>
  </nav>
</footer>
      

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-reindeer">
    <%= link_to image_tag("reindeer.png", alt:"RHM Logo", id:'logo'), root_path, class:'navbar-brand' %>
    <%= link_to "reindeer hunt manager", root_path, class:"navbar-brand", id:'logo-text' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item"><%= link_to "Home", root_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to 'Help', help_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to 'Sign In', new_user_session_path, class:"nav-link" %></li>
        <li class="nav-item"><%= link_to 'Sign Up', new_user_registration_path, class:"nav-link" %></li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title yield(:title)%></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim'%>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <br />
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
    <%= render 'layouts/footer'%>
  </body>
</html>

app/views/layouts/hello_world.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReactOnRailsWithWebpacker</title>
    <%= csrf_meta_tags %>
    <%= javascript_pack_tag 'hello-world-bundle' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rosters/_form.html.erb
<%= form_with(model: roster, local: true) do |form| %>
  <% if roster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(roster.errors.count, "error") %> prohibited this roster from being saved:</h2>

      <ul>
      <% roster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :extra_attributes %>
    <%= form.text_field :extra_attributes %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rosters/edit.html.erb
<h1>Editing Roster</h1>

<%= render 'form', roster: @roster %>

<%= link_to 'Show', @roster %> |
<%= link_to 'Back', rosters_path %>

app/views/rosters/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rosters</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Extra attributes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rosters.each do |roster| %>
      <tr>
        <td><%= roster.name %></td>
        <td><%= roster.extra_attributes %></td>
        <td><%= link_to 'Show', roster %></td>
        <td><%= link_to 'Edit', edit_roster_path(roster) %></td>
        <td><%= link_to 'Destroy', roster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Roster', new_roster_path %>

app/views/rosters/new.html.erb
<h1>New Roster</h1>

<%= render 'form', roster: @roster %>

<%= link_to 'Back', rosters_path %>

app/views/rosters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @roster.name %>
</p>

<p>
  <strong>Extra attributes:</strong>
  <%= @roster.extra_attributes %>
</p>

<%= link_to 'Edit', edit_roster_path(@roster) %> |
<%= link_to 'Back', rosters_path %>

app/views/static_pages/about.html.erb
<% provide(:title, "About")%>

<h1>About</h1>
<p>
    The Reindeer Hunt manager is a program designed by Kyle Anderson to manage Reindeer Hunts.<br>
    The idea for this application came from the need for faster, more automated processes for managing
    the large volume of students in the Reindeer Hunt. <br>
    Originally, this problem was solved with a desktop application created using
    Windows Presentation Foundation and the Microsoft .NET framework.<br>
    Since then it was decided to create an equivalent web application for greater usability
    and compatibility across platforms.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>

<h1>Help</h1>
<p>Contact Kyle Anderson: <a href="mailto:kyle.r.anderson@outlook.com">kyle.r.anderson@outlook.com</a>.</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
    <h1>Reindeer Hunt Manager</h1>
    <p>
        Welcome to the Reindeer Hunt Manager, an application designed to manage the annual Sacred Heart Reindeer Hunt
        competition or an equivalent sort of competition.
    </p>

    <h2>Competition Description</h2>
    <p>
        The Reindeer Hunt is an event that is run annually at Sacred Heart High School in Stittsville, Ontario.
        In this competition, students are paired with each other in matches and are tasked with pinning 
        their pair with a clotehspin in order to eliminate that person from the hunt.<br>
        The participant who pins their opponent advances to the next round in which they will play against
        other winners.
    </p>

    <%= link_to 'Sign up', new_user_registration_path, class: "btn btn-reindeer btn-primary btn-lg", role: 'button' %>
</div>